### PR TITLE
Port to Gtk+3

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
@quozl  please review!

### CODE REVIEW

**Comment by quozl** [comment]
* [ ] remove UserInfo.txt from .gitignore?
* [ ] new code in Juego.py not flake8?

**Comment by yell0wfl4sh** [comment]
@quozl added UserInfo.text and some flake8 fixes in Juego.py ( especially new changes)

**Comment by quozl** [comment]
Reviewed to 96de6b4.  You've changed content in UserInfo.txt why?  Perhaps this activity should create the file if it does not exist.

**Comment by yell0wfl4sh** [comment]
Since UserInfo.txt stores information after running the activity, I think it would be best if the file is not added on GitHub. If the file is not present it will be created. @quozl please review!

**Pull request merged**
